name: VoiceIt
options:
  bundleIdPrefix: com.voiceit
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  
settings:
  SWIFT_VERSION: "6.0"
  SWIFT_STRICT_CONCURRENCY: complete
  IPHONEOS_DEPLOYMENT_TARGET: "18.0"
  TARGETED_DEVICE_FAMILY: "1,2"
  PRODUCT_NAME: VoiceIt
  INFOPLIST_FILE: VoiceIt/Resources/Info.plist
  ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  VoiceIt:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: VoiceIt
        excludes:
          - "Resources/Info.plist"
    info:
      path: VoiceIt/Resources/Info.plist
      properties:
        CFBundleDisplayName: Voice It
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: voiceitPurple
          UIImageName: shield.checkered
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Voice It needs access to your microphone to record voice notes as evidence."
        NSCameraUsageDescription: "Voice It needs access to your camera to capture photos and videos as evidence."
        NSPhotoLibraryUsageDescription: "Voice It needs access to your photo library to save and retrieve evidence securely."
        NSLocationWhenInUseUsageDescription: "Voice It can optionally record your location with evidence for documentation purposes."
        NSLocationAlwaysAndWhenInUseUsageDescription: "Voice It can optionally track your location in the background for safety purposes."
        NSFaceIDUsageDescription: "Voice It uses Face ID to securely protect your evidence and personal information."
        UIBackgroundModes:
          - location
    settings:
      SWIFT_VERSION: "6.0"
      SWIFT_STRICT_CONCURRENCY: complete
      PRODUCT_BUNDLE_IDENTIFIER: com.voiceit.app
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
    scheme:
      testTargets:
        - VoiceItTests
      gatherCoverageData: true
    capabilities:
      - com.apple.BackgroundModes
      - com.apple.Keychain
    entitlements:
      path: VoiceIt/VoiceIt.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.voiceit.app

  VoiceItTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - VoiceItTests
    dependencies:
      - target: VoiceIt
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/VoiceIt.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/VoiceIt

schemes:
  VoiceIt:
    build:
      targets:
        VoiceIt: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - VoiceItTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

